version: "3.8"

volumes:
  rabbitmq_data:

services:

  ###################################
    #The Student microservice
  ###################################

  student:
    build:
      context: ./
      dockerfile: student.Dockerfile
    image: shchong/student:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/student
      PYTHONUNBUFFERED: 1
    ports:
     - "5004:5004"


  
  ###################################
    #The Company microservice
  ###################################
  
  company:
    build:
      context: ./
      dockerfile: company.Dockerfile
    image: shchong/company:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/company
      PYTHONUNBUFFERED: 1
    ports:
     - "5002:5002"
  
  ###################################
    #The Job microservice
  ###################################


  job:
    build:
      context: ./
      dockerfile: job.Dockerfile
    image: shchong/job:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/job
      PYTHONUNBUFFERED: 1
    ports:
     - "5003:5003"

  

  ###################################
    #The Application microservice
  ###################################


  application:
    build:
      context: ./
      dockerfile: application.Dockerfile
    image: shchong/application:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/application
      PYTHONUNBUFFERED: 1
    ports:
     - "5001:5001"
  

  ###################################
    #RabbitMQ: The messaging broker  
  ###################################
    

  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  


  ###################################
    #The student_history microservice
  ###################################

  student_history:
    build:
      context: ./
      dockerfile: student_history.Dockerfile
    image: shchong/student_history:esd
    restart: always
    depends_on:
     - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/record_one
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  

  ###################################
    #The company_history microservice
  ###################################


  company_history:
    build:
      context: ./
      dockerfile: company_history.Dockerfile
    image: shchong/company_history:esd
    restart: always
    depends_on:
     - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/history_one
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
  



  ##########################################
    #The apply_for_internship microservice
  ##########################################


  apply_for_internship:
    build:
      context: ./
      dockerfile: apply_for_internship.Dockerfile
    image: shchong/apply_for_internship:esd
    restart: always
    depends_on:
      - student
      - job
      - company
      - application
      - rabbitmq

    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      applicationCheck_URL: "http://application:5001/application_check"
      jobCheck_URL: "http://job:5003/job_check"
      studentCheck_URL: "http://student:5004/student_check"
      application_URL: "http://application:5001/application" 
      companyCheck_URL: "http://company:5002/company_check"
      PYTHONUNBUFFERED: 1
    ports:
     - "5100:5100"


  

  ##########################################
    #The create_job_posting microservice
  ##########################################


  create_job_posting:
    build:
      context: ./
      dockerfile: create_job_posting.Dockerfile
    image: shchong/create_job_posting:esd
    restart: always
    depends_on:
      - job
      - company
    
    environment:
      company_URL: "http://company:5002/company_check"
      job_URL: "http://job:5003/job"
      PYTHONUNBUFFERED: 1
    ports:
     - "5200:5200"

  ###################################
    #The Email microservice
  ###################################

  email1:
    build:
      context: ./
      dockerfile: email1.Dockerfile
    image: shchong/email1:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
     - "5007:5007"



  




      



